// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtt05zPQIHmA3QtObfUvmSGV6VjABAvps',
    appId: '1:278319877545:web:603cd2046fd1b87048c8b8',
    messagingSenderId: '278319877545',
    projectId: 'evolveyou-prod',
    authDomain: 'evolveyou-prod.firebaseapp.com',
    storageBucket: 'evolveyou-prod.firebasestorage.app',
    measurementId: 'G-6SRSV360HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtt05zPQIHmA3QtObfUvmSGV6VjABAvps',
    appId: '1:278319877545:android:ANDROID_APP_ID_HERE',
    messagingSenderId: '278319877545',
    projectId: 'evolveyou-prod',
    storageBucket: 'evolveyou-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtt05zPQIHmA3QtObfUvmSGV6VjABAvps',
    appId: '1:278319877545:ios:0d0e407e87e0ee3248c8b8',
    messagingSenderId: '278319877545',
    projectId: 'evolveyou-prod',
    storageBucket: 'evolveyou-prod.firebasestorage.app',
    iosBundleId: 'evolveyou-ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtt05zPQIHmA3QtObfUvmSGV6VjABAvps',
    appId: '1:278319877545:ios:0d0e407e87e0ee3248c8b8',
    messagingSenderId: '278319877545',
    projectId: 'evolveyou-prod',
    storageBucket: 'evolveyou-prod.firebasestorage.app',
    iosBundleId: 'evolveyou-ios',
  );
}

